### ISSUE TITLE
scallion.exe hangs on kernel compile

### ISSUE THREAD

**Issue by azazar** [lachesis/scallion#74]
It hangs, when I pass following regex as argument: `[abcd][abcd][abcd][abcd][abcd][abcd][abcd][abcd][abcd][abcd]aa[abcd][abcd][abcd]`

```
$ mono scallion.exe [abcd][abcd][abcd][abcd][abcd][abcd][abcd][abcd][abcd][abcd]aa[abcd][abcd][abcd][abcd]
Cooking up some delicions scallions...
Putting 1024 patterns into 62 buckets.
Using kernel optimized from file kernel.cl (Optimized4_9)
Using work group size 64
Compiling kernel... 
```

**Comment by lachesis** [comment]
That is a seriously degenerate case. :P The regex compilation code compiles this into a crazy bitwise prefix matching thing. @freethenation can probably explain more if you are interested, but as it turns out, you're asking for a very complicated match. I'm going to WONTFIX this for now, but it's nice to have a clear repro case if we come back to this.
